# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2da415fb5234d92e873a4062a6c73908e8670e724b22150b264d93cad8245edda76fedb04783e87de2b43226250ccf255faa213801d2b242371d9b60f2f83b58

test:
  secret_key_base: 0f598639f4063df7053599b97665fc2342cc8ba052e6fe3e441bbe7d606ff2b7bfa64105b9d90f1677f0b9828b58a13fda7cdbe466e88fc9cbbc11653ba62cdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
